"""
Django settings for notification project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sgw0m6a6w9fbleym8s+xx6vu403x(znfvpvd^dvv9y)i7jxnrm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'push_notification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notification.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# FIREBASE_CONFIG = {
#   "type": "service_account",
#   "project_id": "notification-2a4ae",
#   "private_key_id": "5e65d854517adebdf035f2bdce36bc2bba7e08c2",
#   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDUw6Yv7cmOhAdy\nlzZgPJMrRKIBmZDxzEcMGLguJ2ldqRmTGF+e0husWEANkAo0oWiHaR0PPl8GWBMc\nG0K0NICTpMy5/bl6hOYKFX6tcTOfFWPdBvveFtYw291LCy+6JalEXrO6qmAFugxL\noJ0uqV8nMT43wqqr72sgHkMC+BNEVDGq8FTnnUYRBxFOyTGSMz1cVJRBVWcnw044\nMU3xzTDieHIjRfOX3stun/eeeNvg28YadMPpxuQQ2IJAmGPRDbycUHmvvtBk8mWC\nQYqL9gvSKzXvdqHnP1prZWTRBmeVyZq1qTUQ1aVg3cDxropkQjJdriqrvyje/zFE\n2+PBjOGbAgMBAAECggEANi9vmwQ5kTiRtv7Io+C5cEsF4VdtQQ9PxsZi3ao+3NIM\nh9gsvgNvdchx46Jb3wR+XQIJmxC83Z4/m6hbqA448qEFXJbADnJbLZVE0kIirfCi\nIq+9JFX3jbDo3kxGhudBgP6HUlJCqyKzL+2DKleLOq2BVW0XzzrlsuPSGCb6rSs2\n8wGlhvL9kHXn5uAsRJnJeBbqd2ETZY85/UtzebL+7gYLFt3/WzaeXqpHG8OkHrei\nzgr6dUaxWaowcqBXVcbyisvqjj+cnybFQSdVy2rvZ5I5vJB4NgLumi9gWfiQt7mJ\n/xp9ADiJUUrPDkaaG4gzIxboGTUt57vcIkWK8wSs4QKBgQD4QfQ2hDfBnHGExG15\nzcONxewo2nOmIQ3lWJ1ExG32g4JKkf/8nfhZQMqIx8cgW5Hb0VUHLiJx1m8xyM8z\nAPTodHBZJH2lls1ACVWgc8gyAAu36hvsSyIb+rcD7HvTEN4Mq3dGu70oQuDWplyv\nc2Vg830ShYNDVSnG9JbdOfZW4QKBgQDbZlJ8oa0vLyYyXRgwlrhnEDl96wa8zmCw\naOagj8gN1ilnrJ6nWGnqO8AxdnWb6zLWtiZ4e3sdqABS0zwUwASzRl5DEUK70phE\nhoJ7Oh5kj6lDANWITSy34KRHHpT0FhVVFGkR2ice4+5yMiPP6SaFw1YApFrJKBpk\ngY5IzfMT+wKBgQD34PrUGE6HvgpG086vqPlSLMZxwDVrMmPqlQFq8WsOkh7dEEx2\nUtDvZVcVHczAjU3lG2333mO8IK0kG2pvdcwT8ndfOqVOWnWUM/3QWOsSqaMJvvKk\njByBrWNhwpWcmKHuKqLM+JWVhrly+edftCwMkvJWNQNsjrNJGV0thTtnYQKBgQDN\nso07lElOp6HkLivzwht5ZVjBmYxjkApO2sr/Vk51yohfTxQgSWBj30k+FpYFbOnp\nLDW9V+gB0fUbsjfuLGk7u4m8z34FolhoRsQmzEKafaZvz2Rjuhdm/hKHK0Dz55Bw\niAZKWoG7EHAKWMACudEIMC99wpnrZtH30Q+Zap2v6QKBgQCt51jZRqEfGvFQa2Ye\n8ZLzqDYyhIjTmw62JDczPm6D6UuKqIZRduRVdIl21R1kNpoR2yeaovh521MOKGKh\nuRKyxTRhI2XztXjEVmqJIxl4AE8d6HuNImUmTolI62lXtz2QwFy+Gc0GUoU/ucST\nntX3KA8vTbTI2nOOSlu7AoRdlw==\n-----END PRIVATE KEY-----\n",
#   "client_email": "firebase-adminsdk-vrify@notification-2a4ae.iam.gserviceaccount.com",
#   "client_id": "100119579224850448500",
#   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#   "token_uri": "https://oauth2.googleapis.com/token",
#   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-vrify%40notification-2a4ae.iam.gserviceaccount.com",
#   "universe_domain": "googleapis.com"
# }
